# Generated by Django 4.2.5 on 2023-10-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
