# Generated by Django 4.2.5 on 2023-10-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='data',
            new_name='questions',
        ),
    ]
